[2025-03-11T00:33:49.306+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-11T00:33:49.315+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: redfin_analytics_dag.tsk_extract_redfin_data manual__2025-03-11T00:33:45.250110+00:00 [queued]>
[2025-03-11T00:33:49.320+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: redfin_analytics_dag.tsk_extract_redfin_data manual__2025-03-11T00:33:45.250110+00:00 [queued]>
[2025-03-11T00:33:49.320+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-03-11T00:33:49.335+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): tsk_extract_redfin_data> on 2025-03-11 00:33:45.250110+00:00
[2025-03-11T00:33:49.342+0000] {standard_task_runner.py:72} INFO - Started process 7791 to run task
[2025-03-11T00:33:49.345+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'redfin_analytics_dag', 'tsk_extract_redfin_data', 'manual__2025-03-11T00:33:45.250110+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/redfin_analytics.py', '--cfg-path', '/tmp/tmprnnvp8vl']
[2025-03-11T00:33:49.346+0000] {standard_task_runner.py:105} INFO - Job 43: Subtask tsk_extract_redfin_data
[2025-03-11T00:33:49.386+0000] {task_command.py:467} INFO - Running <TaskInstance: redfin_analytics_dag.tsk_extract_redfin_data manual__2025-03-11T00:33:45.250110+00:00 [running]> on host ip-172-31-7-71.eu-west-2.compute.internal
[2025-03-11T00:33:49.446+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='dengineer420@gmail.com' AIRFLOW_CTX_DAG_OWNER='Rahul' AIRFLOW_CTX_DAG_ID='redfin_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_extract_redfin_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T00:33:45.250110+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-11T00:33:45.250110+00:00'
[2025-03-11T00:33:49.447+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-11T00:33:49.447+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-11T00:33:49.447+0000] {logging_mixin.py:190} INFO - Current task name:tsk_extract_redfin_data state:running start_date:2025-03-11 00:33:49.315237+00:00
[2025-03-11T00:33:49.448+0000] {logging_mixin.py:190} INFO - Dag name:redfin_analytics_dag and current dag run status:running
[2025-03-11T00:33:49.448+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-11T00:38:26.805+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-03-11T00:38:26.806+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-11T00:38:26.811+0000] {process_utils.py:132} INFO - Sending 15 to group 7791. PIDs of all processes in the group: [7791]
[2025-03-11T00:38:26.811+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 7791
[2025-03-11T00:38:26.811+0000] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-11T00:38:26.828+0000] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/home/ubuntu/redfin_venv/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/__main__.py", line 62, in main
    args.func(args)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ubuntu/airflow/dags/functions.py", line 21, in extract_data
    chunk.to_csv(output_file_path, index = False)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 270, in save
    self._save()
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 275, in _save
    self._save_body()
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 313, in _save_body
    self._save_chunk(start_i, end_i)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 320, in _save_chunk
    res = df._get_values_for_csv(**self._number_format)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/pandas/core/frame.py", line 1410, in _get_values_for_csv
    mgr = self._mgr.get_values_for_csv(
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 466, in get_values_for_csv
    return self.apply(
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 363, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/pandas/core/internals/blocks.py", line 780, in get_values_for_csv
    result = get_values_for_csv(
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 7834, in get_values_for_csv
    values = values.astype(str)
  File "/home/ubuntu/redfin_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-03-11T00:38:26.912+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-11T00:38:26.944+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=7791, status='terminated', exitcode=0, started='00:33:49') (7791) terminated with exit code 0
